### ISSUE TITLE
Configure Micronaut Lifecylce per Property or per Try

### ISSUE THREAD

**Issue by jlink** [jqwik-team/jqwik-micronaut#4]
There should be a way to configure if things like transactions will be rolled-back per try or per property.
Currently, everything is done per property, ie having more than one try in those tests will fail:

```java
@JqwikMicronautTest(transactionMode = TransactionMode.SINGLE_TRANSACTION)
@DbProperties
class JpaSingleTransactionNoSetupTest {
    @Inject
    private EntityManager entityManager;

    @AfterProperty
    void tearDown() {
        // check test was rolled back
        final CriteriaQuery<Book> query = entityManager.getCriteriaBuilder().createQuery(Book.class);
        query.from(Book.class);
        assertThat(entityManager.createQuery(query).getResultList()).isEmpty();
    }

    @Property(tries = 10)
    void testPersistOne() {
        System.out.println("#### testPersistOne");
        final Book book = new Book();
        book.setTitle("The Stand");
        entityManager.persist(book);

        final CriteriaQuery<Book> query = entityManager.getCriteriaBuilder().createQuery(Book.class);
        query.from(Book.class);
        assertThat(entityManager.createQuery(query).getResultList().size()).isEqualTo(1);
    }
}
```

This fails with 
```
JpaSingleTransactionNoSetupTest:testPersistOne = 
  org.opentest4j.AssertionFailedError:
    expected: 1
     but was: 2
```
in the second try.

**Comment by Nahuel92** [comment]
I can take a look. Off the top of my head, we could add an extra boolean parameter to `JqwikMicronautTest` and then check in each hook (property and try) the value and, depending on it, execute one hook or the other.

I will play around the idea and see how that works and will let you know.

**Comment by Nahuel92** [comment]
Hi, just wanted to say that I have been busy this week but I expect to come back with a solution for this issue after this weekend.

**Comment by Nahuel92** [comment]
Hi, I have created a [feature branch](https://github.com/jqwik-team/jqwik-micronaut/tree/feature/%234_Configure_Micronaut_Lifecycle_per_Property_or_per_Try) to address this issue.
I would like to have your feedback on it because, even though the provided test now passes correctly, I still need to improve the code but first I want to make sure this adds the requested behavior.
