### ISSUE TITLE
Prepare for Release 1.0

### ISSUE THREAD

**Issue by jlink** [jqwik-team/jqwik-micronaut#8]
- [x] Update to use jqwik 1.7.4
- [x] Use latest Gradle
- [x] Create sample in [samples repo](https://github.com/jqwik-team/jqwik-samples)
- [x] Set version to 1.0.0

Anything else, @Nahuel92?

**Comment by Nahuel92** [comment]
I will go ahead and will update dependencies and set version to 1.0.0.
Regarding the sample project, I am a little divided.

To me, everything under src/test/java is really a project sample. In my mind, those tests should be moved to a sample project and its pipeline should build it and test it against multiple Micronaut versions (to check for compatibility issues).

Then, we could add unit tests to the extension. They would be super simple, though, basically making sure the right methods are invoked by the right extension hooks.

Not sure if that makes sense, I would like to hear your thoughts on this so that we can move forward with the release.
For now, I will go ahead and do items 2 and 4.

**Comment by jlink** [comment]
The samples in the samples repo are just for showing the set up, eg Gradle or pom file and source structure. A place where people go to init their own project. Extended examples are a different thing IMO.

**Comment by Nahuel92** [comment]
> The samples in the samples repo are just for showing the set up, eg Gradle or pom file and source structure. A place where people go to init their own project. Extended examples are a different thing IMO.

Ok I will do that (hopefully) during the weekend.

**Comment by jlink** [comment]
I can release 1.0.0 without it, if you want.

**Comment by Nahuel92** [comment]
I have created samples for Gradle and Maven but I can't push my feature branch into that repo to create a PR.
Not sure how you want to handle this, I could clone the repo and then you can merge it into the `jqwik-samples` if you like.

**Comment by jlink** [comment]
> I have created samples for Gradle and Maven but I can't push my feature branch into that repo to create a PR. Not sure how you want to handle this, I could clone the repo and then you can merge it into the `jqwik-samples` if you like.

Standard procedure for PRs in OSS is to create them on a clone of the original repo. The difference here is that you have committing rights but you don't have those on `jqwik-samples`. I would like to keep it this way, because the repo is not (yet) set up to automatically validate through GH actions. It requires some manual work to make sure nothing fails :-/ 
I'm happy to give you push rights as soon as this has changed - but I have more pressing things to work on in my little spare time.

**Comment by Nahuel92** [comment]
> > I have created samples for Gradle and Maven but I can't push my feature branch into that repo to create a PR. Not sure how you want to handle this, I could clone the repo and then you can merge it into the `jqwik-samples` if you like.
> 
> Standard procedure for PRs in OSS is to create them on a clone of the original repo. The difference here is that you have committing rights but you don't have those on `jqwik-samples`. I would like to keep it this way, because the repo is not (yet) set up to automatically validate through GH actions. It requires some manual work to make sure nothing fails :-/ I'm happy to give you push rights as soon as this has changed - but I have more pressing things to work on in my little spare time.

That's fine, I don't really need those permissions. This is the first time I had to create a PR in an OSS project and I asked because I wasn't sure how to proceed.
Check out that project, hopefully I have created a PR the right way (if not, just let me know).

**Comment by jlink** [comment]
Cool. I’ll release jqwik-micronaut 1.0.0 and then merge the PR in samples.

**Comment by jlink** [comment]
1.0.0 has been released

**Comment by jlink** [comment]
Everything done. Thanks for the great work @Nahuel92 !

**Comment by Nahuel92** [comment]
Thanks man, it was great to work with you to release this extension.
